def aes128_cfb128_decrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes128_cfb128_encrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes128_cfb8_decrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes128_cfb8_encrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes128_ctr128(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes256_cfb128_decrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes256_cfb128_encrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes256_cfb8_decrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes256_cfb8_encrypt(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def aes256_ctr128(data: bytes, key: bytes, nonce: bytes) -> bytes: ...
def pbkdf2_sha1(data: bytes, salt: bytes, rounds: int, klen: int) -> bytes: ...
def pbkdf2_sha256(data: bytes, salt: bytes, rounds: int, klen: int) -> bytes: ...
def pbkdf2_sha384(data: bytes, salt: bytes, rounds: int, klen: int) -> bytes: ...
def pbkdf2_sha512(data: bytes, salt: bytes, rounds: int, klen: int) -> bytes: ...
