name: build

on: workflow_dispatch

env:
  MATURIN_VERSION: 1.3.0
  PY_ALL: 3.8 3.9 3.10 3.11 3.12 pypy3.8 pypy3.9 pypy3.10

jobs:
  wheel-unix:
    name: wheel ${{ matrix.platform || matrix.os }}(${{ matrix.target }}) - ${{ matrix.manylinux || 'auto' }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        target: [x86_64, aarch64]
        manylinux: [auto]
        include:
          - os: ubuntu
            platform: linux
          - os: macos
            interpreter: 3.8 3.9 3.10 3.11 3.12 pypy3.9 pypy3.10
          - os: ubuntu
            platform: linux
            target: aarch64
            container: messense/manylinux_2_24-cross:aarch64
          - os: ubuntu
            platform: linux
            target: x86_64
            manylinux: musllinux_1_1
          - os: ubuntu
            platform: linux
            target: aarch64
            manylinux: musllinux_1_1
        exclude:
          - os: windows
            target: aarch64
    steps:
      - uses: actions/checkout@v3
      - uses: pyo3/maturin-action@v1
        with:
          maturin-version: v${{ env.MATURIN_VERSION }}
          command: build
          args: --release --interpreter ${{ matrix.interpreter || env.PY_ALL }}
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux || 'auto' }}
          container: ${{ matrix.container }}
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels

  wheel-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - uses: pyo3/maturin-action@v1
        with:
          maturin-version: v${{ env.MATURIN_VERSION }}
          command: build
          args: --release --interpreter ${{ env.PY_ALL }}
          target: x86_64
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels
